Issue #30 Solved
SaiyamTuteja/Faculty_Evaluation_System pull request #35
Opened 2024-05-16 15:03 UTC by anushkasaxena07

## PR Description

The issue with the existing code is that it directly inserts user input into SQL queries, making it vulnerable to SQL injection attacks. To address this, the code needs to be refactored to use prepared statements with parameter binding. Prepared statements separate SQL logic from data, preventing malicious SQL code injection.

Solution:

Here's how to solve the issue:

1. save_progress() function:
   - Refactor the code to use a prepared statement with parameter binding.
   - Bind parameters to the statement to ensure safe execution.
   - Execute the statement.

2. delete_progress() function:
   - Refactor to use a prepared statement with parameter binding.
   - Bind the id parameter to the statement.
   - Execute the statement.

3. save_restriction() function:
   - Loop through the $rid array to handle multiple rows.
   - Use prepared statements with parameter binding for both INSERT and UPDATE operations.
   - Execute the statements within the loop.

4. save_evaluation() function:
   - Use a prepared statement with parameter binding to insert data into evaluation_list.
   - Loop through $qid to handle multiple question evaluations.
   - Use prepared statements with parameter binding to insert data into evaluation_answers.
   - Execute the statements within the loop.

5. get_class() function:
   - Refactor to use a prepared statement with parameter binding.
   - Bind parameters for $fid and academic_id.
   - Execute the statement and fetch results.

6. get_report() function:
   - Refactor to use a prepared statement with parameter binding.
   - Bind parameters for academic_id, faculty_id, subject_id, and class_id.
   - Execute the statement to get evaluation answers.
   - Use a prepared statement to get the total answered rows.
   - Calculate percentages and return the JSON-encoded data.

By implementing these changes, it ensures that user input is properly sanitized, and the application is protected from SQL injection attacks. Prepared statements with parameter binding handle user data safely, preventing malicious SQL injection attempts.

Related Issues: Issue for which you are raising a PR for Avoiding SQL injections using prepared statements of MySQLi #30
Closes https://github.com/SaiyamTuteja/Faculty_Evaluation_System/issues/30
## Issue
#30 

## Checklist
[ x] I have gone through the [contributing guide](https://github.com/SaiyamTuteja/Faculty_Evaluation_System/blob/main/CONTRIBUTING.md)
[ x] I have updated my branch and synced it with project main branch before making this PR
[x ] Is this a bug fix/enhancement/documentation changes
[ x] Part of GSSOC
[ x] Tested for any breaking changes
[x ] Other relevant checks completed
## Undertaking
I declare that:

The content I am submitting is original and has not been plagiarized.
No portion of the work has been copied from any other source without proper attribution.
The work has been checked for plagiarism, and I assure its authenticity.
I understand that any violation of this undertaking may have legal consequences that I will bear and could result in the withdrawal of any recognition associated with the work.

[ x] I Agree

2024-05-19 07:57 UTC, aswinikalyan30 commented on admin_class.php
> +function login(){
I don't see the initial lines fo the session_start() added to this file - Please cross check and add it:
```
<?php
session_start();
ini_set('display_errors', 1);
Class Action {
	private $db;

	public function __construct() {
		ob_start();
   	include 'db_connect.php';
    
    $this->db = $conn;
	}
	function __destruct() {
	    $this->db->close();
	    ob_end_flush();
	}
```

2024-05-19 08:00 UTC, aswinikalyan30 requested changes

2024-05-19 08:00 UTC, aswinikalyan30 commented
Needs more work - Please let me know if you have any trouble setting it up on your local and we can chat over discord

2024-05-19 12:13 UTC, anushkasaxena07 commented
@aswinikalyan30 sorry for my negligence please have a look now 
is it fine?

2024-05-19 14:34 UTC, aswinikalyan30 requested changes

2024-05-19 14:34 UTC, aswinikalyan30 commented on admin_class.php
> +        $stmt->bind_param($data_types."i", ...$data_values, $chk->fetch_array()['id']);
Fatal error: Cannot use positional argument after argument unpacking in /Applications/MAMP/htdocs/Faculty_Evaluation_System-main/admin_class.php on line 354
Getting this error

2024-05-19 14:34 UTC, aswinikalyan30 commented on admin_class.php
> +        $stmt->bind_param($data_types."i", ...$data_values, $chk->fetch_array()['id']);
Ran it on my local and got this error - How are you testing your changes?

2024-05-19 14:34 UTC, aswinikalyan30 commented on admin_class.php
> +<?php
Causing syntax issues on this line - remove it

2024-05-19 14:34 UTC, aswinikalyan30 commented on manage_user.php
> +    $('#manage-user').submit(function(e){
This function calls an empty url - but I see the query is written on top - how are you testing any of your changes?
Going forward I need screenshots added to the PR to see what output you are seeing on screen

2024-05-23 14:23 UTC, aswinikalyan30 commented
Hey @anushkasaxena07 - any progress?

2024-05-23 17:12 UTC, anushkasaxena07 commented
Still working on it

2024-05-28 05:23 UTC, aswinikalyan30 commented
Hey @anushkasaxena07 this has been open for too long, if you're not able to solve it will assign to someone else

2024-05-28 05:26 UTC, aswinikalyan30 commented
Closing this PR as no working changes are made for more than 2 weeks and is blocking contributions from others

2024-05-28 05:26 UTC, closed without merging