Created Contact Us Page
SaiyamTuteja/Faculty_Evaluation_System pull request #56
Opened 2024-05-27 17:24 UTC by mahek0620

Issue No 54 - Implementatio of Contact Us Page
![Screenshot 2024-05-27 224418](https://github.com/SaiyamTuteja/Faculty_Evaluation_System/assets/136893675/5e8f6e81-4a1e-4b53-8061-f16cf9f5986c)

2024-05-28 05:21 UTC, aswinikalyan30 commented
@mahek0620 can you link all the issues you are solving here?
Also add screenshots for all changes made?

2024-05-28 05:58 UTC, mahek0620 commented
I have already uploaded screenshot above. 
Clicking the 'Contact Us' button will open a new page containing contact details such as phone number, email, and address, along with an attached form to fill the details. It allows users to offer feedback on the system, which can be valuable for making improvements and addressing user concerns. Users can report any technical problems they encounter, ensuring that issues are documented and can be resolved efficiently. It provides a direct channel for users, such as faculty members, students, and administrators, to seek assistance or report issues.
Note: For adding the social media links, a footer should be made on the website and social media links should be shared there instead of sharing in the Contact Us button. I will open a new issue and will fix that issue if you agree.

2024-05-28 06:02 UTC, aswinikalyan30 commented
Yes, I do understand that, I wanted you to add it for the reset email and password that you had implemented. Which is linked to another issue

2024-05-28 06:08 UTC, mahek0620 commented
![image](https://github.com/SaiyamTuteja/Faculty_Evaluation_System/assets/136893675/daee3ceb-1545-4c16-a254-2d20572f7309)
![image](https://github.com/SaiyamTuteja/Faculty_Evaluation_System/assets/136893675/2fa844ce-846f-4a70-9cfe-c7bbd1f1d89f)
Here is the screenshot of login page with Forgot Password option

2024-05-28 06:19 UTC, aswinikalyan30 commented
In issue #52 you mentioned you will implement a "sign in with google" button - Is that also added on this PR itself?

2024-05-28 06:19 UTC, mahek0620 commented
@aswinikalyan30 Thank you for your feedback. I will surely add the logo

2024-05-28 06:20 UTC, mahek0620 commented
can you please assign signin with google to one more person as I am facing difficulties in doing that

2024-05-28 06:40 UTC, aswinikalyan30 commented
Sure, will update that issue only for reset

2024-05-29 13:01 UTC, mahek0620 commented
@aswinikalyan30 I have added logo in the contactUs page

2024-05-29 14:42 UTC, aswinikalyan30 requested changes
Please update the login.php file , otherwise looks good!

2024-05-29 14:42 UTC, aswinikalyan30 commented on login.php
> +    <hr id="title_hr" class="mx-auto">
Add logo (from prev (line 51)

2024-05-29 14:42 UTC, aswinikalyan30 commented on login.php
> +                <input type="password" id="password" name="password" value="<?= htmlspecialchars($_POST['password'] ?? "", ENT_QUOTES) ?>" required="required">
There was some code written by a prev contributor for toggle of password "fas fa-eye" - please don't scrape whatever was written before. I can see the different icons that were there are removed. It is okay to make additions to the file, this looks like is rebranded.

2024-05-30 15:59 UTC, mahek0620 commented
@aswinikalyan30 as you mentioned that There was some code written by a prev contributor for toggle of password "fas fa-eye" - please written before keeping that in mind I have modified the code kindly review it

2024-06-01 06:25 UTC, mahek0620 commented
@aswinikalyan30 can you please review it

2024-06-01 06:36 UTC, aswinikalyan30 commented
Sure.

2024-06-01 06:39 UTC, aswinikalyan30 approved these changes
Great work!

2024-06-01 06:39 UTC, merged